<a href="https://colab.research.google.com/github/faryadshahfs-byte/student-performance-prediction-ml/blob/main/%20Student_performance_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Multivariant Linear Regression

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv('/content/drive/MyDrive/AI   ML 2026/Multiple Linear Regression - Sheet1.csv')
df

   Study Hours  Attendance Assignments  Exam Marks
0            1          60           2          40
1            2          65           3          48
2            3          70           4          55
3            4          72           5          60
4            5          75           5          65
5            6          80           6          72
6            7          82          na          77
7            8          85           8          83
8            9          90           9          89
9           10          95          10          95

In [11]:
df['Assignments'] = pd.to_numeric(df['Assignments'], errors='coerce')
median_assignments = df['Assignments'].median()
df['Assignments'].fillna(median_assignments, inplace=True)
print(df['Assignments'].median())
df

5.0

/tmp/ipykernel_349/4236955916.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Assignments'].fillna(median_assignments, inplace=True)

   Study Hours  Attendance  Assignments  Exam Marks
0            1          60          2.0          40
1            2          65          3.0          48
2            3          70          4.0          55
3            4          72          5.0          60
4            5          75          5.0          65
5            6          80          6.0          72
6            7          82          5.0          77
7            8          85          8.0          83
8            9          90          9.0          89
9           10          95         10.0          95

In [18]:
from sklearn import linear_model
lr = linear_model.LinearRegression()
lr.fit(df[['Study Hours','Attendance','Assignments']], df['Exam Marks'])

LinearRegression()

In [29]:
lr.predict([[6.5,82,9]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([74.73125098])

In [35]:
lr.score(df[['Study Hours','Attendance','Assignments']], df['Exam Marks'])

0.9990438634641752

In [31]:
lr.coef_

array([ 3.78221387,  0.61108502, -0.07937999])

In [32]:
lr.intercept_

np.float64(0.7523093784247976)

In [34]:
Marks = 3.78221387 * 6.5 + 0.61108502 * 82 -0.07937999 * 9
Marks

73.978941885