In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv("/content/drive/MyDrive/AI_ML_Projects 2026/Data/Student_Performance_Prediction/student_performance.csv")

df.head()

   Study_Hours  Attendance  Assignments  Quiz_Score  Exam_Marks
0            7          92            1          68          73
1            4          99            6          77          78
2            8          71            5          42          76
3            5          95            3          55          72
4            7          63            7          69          79

In [4]:
X = df[['Study_Hours',
        'Attendance',
        'Assignments',
        'Quiz_Score']]

y = df['Exam_Marks']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [6]:
model = LinearRegression()

model.fit(X_train, y_train)

print("Model Ready")

Model Ready

In [7]:
df = pd.read_csv("/content/drive/MyDrive/AI_ML_Projects 2026/Data/Student_Performance_Prediction/student_performance.csv")

df.head()

   Study_Hours  Attendance  Assignments  Quiz_Score  Exam_Marks
0            7          92            1          68          73
1            4          99            6          77          78
2            8          71            5          42          76
3            5          95            3          55          72
4            7          63            7          69          79

In [11]:
import joblib

joblib.dump(
    model,
    "/content/drive/MyDrive/AI_ML_Projects 2026/Models/Student_Performance_Prediction/student_performance_model.pkl"
)

print("Model Saved Successfully")

Model Saved Successfully

In [12]:
loaded_model = joblib.load(
    "/content/drive/MyDrive/AI_ML_Projects 2026/Models/Student_Performance_Prediction/student_performance_model.pkl"
)

print("Model Loaded Successfully")

Model Loaded Successfully